name: Lisp Action

on: [push]

jobs:
  build:
    if: github.repository == 'edoigtrd/Lisp-LS'
    runs-on: ubuntu-latest

    container:
      image: fukamachi/sbcl:latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Git
      run: |
        apt-get update
        apt-get install -y git
      
    - name: Install emacs
      run: |
        apt-get install -y emacs

    - name: Install lisp-format
      run: |
        git clone https://github.com/eschulte/lisp-format.git

    - name: Run sblint
      run: ./lisp-format/lisp-format ./main.lisp > ./main.lisp &&
          rm -rf lisp-format

    - name: Commit files
      run: |
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git commit -a -m "Format file"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}
