name: Lisp Action

on: [push]

jobs:
  build:
    if: github.repository == 'edoigtrd/Lisp-LS'
    runs-on: ubuntu-latest

    container:
      image: fukamachi/sbcl:latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Git
      run: |
        apt-get update
        apt-get install -y git
      
    - name: Install emacs
      run: |
        apt-get install -y emacs

    - name: Install lisp-format
      run: |
        git clone https://github.com/eschulte/lisp-format.git

    - name: Run sblint
      run: ./lisp-format/lisp-format ./main.lisp > ./main.lisp &&
          rm -rf lisp-format

    - name: Commit and push
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -A
        git commit -m "Run sblint" || echo "No changes to commit"
        git push https://${{secrets.GITHUB_TOKEN}}@github.com/edoigtrd/Lisp-LS.git || echo "No changes to push"
